// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSids
{
        public const string achievement_quick_killer = "CgkI7PWMhvoCEAIQGg"; // <GPGSID>
        public const string achievement_ten_carat = "CgkI7PWMhvoCEAIQCw"; // <GPGSID>
        public const string achievement_coin_vault = "CgkI7PWMhvoCEAIQRQ"; // <GPGSID>
        public const string achievement_nunchuck_master = "CgkI7PWMhvoCEAIQAw"; // <GPGSID>
        public const string achievement_small_army = "CgkI7PWMhvoCEAIQEA"; // <GPGSID>
        public const string achievement_longbow_master = "CgkI7PWMhvoCEAIQBQ"; // <GPGSID>
        public const string achievement_claw_warrior = "CgkI7PWMhvoCEAIQQA"; // <GPGSID>
        public const string achievement_robin_the_hood = "CgkI7PWMhvoCEAIQKA"; // <GPGSID>
        public const string leaderboard_highest_level_reached = "CgkI7PWMhvoCEAIQaA"; // <GPGSID>
        public const string achievement_close_combat = "CgkI7PWMhvoCEAIQGA"; // <GPGSID>
        public const string achievement_multi_striker = "CgkI7PWMhvoCEAIQNg"; // <GPGSID>
        public const string achievement_sickles_away = "CgkI7PWMhvoCEAIQMA"; // <GPGSID>
        public const string achievement_swat_em = "CgkI7PWMhvoCEAIQKw"; // <GPGSID>
        public const string achievement_dictator = "CgkI7PWMhvoCEAIQSA"; // <GPGSID>
        public const string achievement_slicing_up_the_competition = "CgkI7PWMhvoCEAIQPQ"; // <GPGSID>
        public const string achievement_smacking_em = "CgkI7PWMhvoCEAIQLQ"; // <GPGSID>
        public const string achievement_monarch = "CgkI7PWMhvoCEAIQSg"; // <GPGSID>
        public const string achievement_distant_damage = "CgkI7PWMhvoCEAIQJw"; // <GPGSID>
        public const string achievement_throw_em_if_you_got_em = "CgkI7PWMhvoCEAIQHg"; // <GPGSID>
        public const string achievement_slice__dice = "CgkI7PWMhvoCEAIQEg"; // <GPGSID>
        public const string achievement_army_builder = "CgkI7PWMhvoCEAIQXQ"; // <GPGSID>
        public const string achievement_sticking_with_it = "CgkI7PWMhvoCEAIQYQ"; // <GPGSID>
        public const string achievement_wood_staff_master = "CgkI7PWMhvoCEAIQDQ"; // <GPGSID>
        public const string achievement_and_so_it_begins = "CgkI7PWMhvoCEAIQQQ"; // <GPGSID>
        public const string achievement_wooden_soldier = "CgkI7PWMhvoCEAIQLA"; // <GPGSID>
        public const string achievement_century_mark = "CgkI7PWMhvoCEAIQEw"; // <GPGSID>
        public const string achievement_quest_starter = "CgkI7PWMhvoCEAIQYA"; // <GPGSID>
        public const string achievement_speed_kills = "CgkI7PWMhvoCEAIQFw"; // <GPGSID>
        public const string achievement_6pointed_assassin = "CgkI7PWMhvoCEAIQIg"; // <GPGSID>
        public const string achievement_chain_em_together = "CgkI7PWMhvoCEAIQMw"; // <GPGSID>
        public const string achievement_close_range_power = "CgkI7PWMhvoCEAIQMg"; // <GPGSID>
        public const string achievement_bow__arrow = "CgkI7PWMhvoCEAIQJg"; // <GPGSID>
        public const string achievement_money_hungry = "CgkI7PWMhvoCEAIQRA"; // <GPGSID>
        public const string achievement_recruiter = "CgkI7PWMhvoCEAIQXA"; // <GPGSID>
        public const string achievement_fast_hands = "CgkI7PWMhvoCEAIQGw"; // <GPGSID>
        public const string achievement_stab_wounds = "CgkI7PWMhvoCEAIQNQ"; // <GPGSID>
        public const string achievement_king = "CgkI7PWMhvoCEAIQRw"; // <GPGSID>
        public const string achievement_czar = "CgkI7PWMhvoCEAIQRg"; // <GPGSID>
        public const string achievement_swift__painful = "CgkI7PWMhvoCEAIQGQ"; // <GPGSID>
        public const string achievement_coin_collector = "CgkI7PWMhvoCEAIQQg"; // <GPGSID>
        public const string achievement_tree_hugger = "CgkI7PWMhvoCEAIQLg"; // <GPGSID>
        public const string achievement_powerful_rage = "CgkI7PWMhvoCEAIQUQ"; // <GPGSID>
        public const string achievement_intermediate_archer = "CgkI7PWMhvoCEAIQUw"; // <GPGSID>
        public const string achievement_speed_it_up = "CgkI7PWMhvoCEAIQTg"; // <GPGSID>
        public const string achievement_sai_master = "CgkI7PWMhvoCEAIQBw"; // <GPGSID>
        public const string achievement_attack__retrieve = "CgkI7PWMhvoCEAIQMQ"; // <GPGSID>
        public const string achievement_sharp_distance = "CgkI7PWMhvoCEAIQHw"; // <GPGSID>
        public const string achievement_metal_sai = "CgkI7PWMhvoCEAIQOA"; // <GPGSID>
        public const string achievement_edge_of_the_blade = "CgkI7PWMhvoCEAIQTQ"; // <GPGSID>
        public const string achievement_relentless = "CgkI7PWMhvoCEAIQZQ"; // <GPGSID>
        public const string achievement_martial_artist = "CgkI7PWMhvoCEAIQOg"; // <GPGSID>
        public const string achievement_breaking_through = "CgkI7PWMhvoCEAIQPw"; // <GPGSID>
        public const string leaderboard_highest_total_score = "CgkI7PWMhvoCEAIQDg"; // <GPGSID>
        public const string achievement_two_talons = "CgkI7PWMhvoCEAIQPg"; // <GPGSID>
        public const string achievement_sulton = "CgkI7PWMhvoCEAIQSQ"; // <GPGSID>
        public const string achievement_archer = "CgkI7PWMhvoCEAIQIw"; // <GPGSID>
        public const string achievement_throwing_star_master = "CgkI7PWMhvoCEAIQBA"; // <GPGSID>
        public const string achievement_share_a_gameplay_video_on_facebook = "CgkI7PWMhvoCEAIQEQ"; // <GPGSID>
        public const string achievement_full_potential = "CgkI7PWMhvoCEAIQXw"; // <GPGSID>
        public const string achievement_twenty_carat = "CgkI7PWMhvoCEAIQDA"; // <GPGSID>
        public const string achievement_combatant = "CgkI7PWMhvoCEAIQOw"; // <GPGSID>
        public const string achievement_shuriken = "CgkI7PWMhvoCEAIQIQ"; // <GPGSID>
        public const string achievement_hand_claw_master = "CgkI7PWMhvoCEAIQCA"; // <GPGSID>
        public const string achievement_testing_flight = "CgkI7PWMhvoCEAIQUg"; // <GPGSID>
        public const string achievement_thud = "CgkI7PWMhvoCEAIQKg"; // <GPGSID>
        public const string achievement_blunted_saki = "CgkI7PWMhvoCEAIQNw"; // <GPGSID>
        public const string achievement_grim_reapers = "CgkI7PWMhvoCEAIQNA"; // <GPGSID>
        public const string achievement_sai_anora = "CgkI7PWMhvoCEAIQWQ"; // <GPGSID>
        public const string achievement_adventurer = "CgkI7PWMhvoCEAIQYg"; // <GPGSID>
        public const string achievement_blunt_trauma = "CgkI7PWMhvoCEAIQKQ"; // <GPGSID>
        public const string achievement_chain_gang = "CgkI7PWMhvoCEAIQVg"; // <GPGSID>
        public const string achievement_start_a_battle = "CgkI7PWMhvoCEAIQDw"; // <GPGSID>
        public const string achievement_knock_on_wood = "CgkI7PWMhvoCEAIQVA"; // <GPGSID>
        public const string achievement_ninja_guiding = "CgkI7PWMhvoCEAIQFg"; // <GPGSID>
        public const string achievement_mach_10 = "CgkI7PWMhvoCEAIQHA"; // <GPGSID>
        public const string achievement_getting_quick = "CgkI7PWMhvoCEAIQTw"; // <GPGSID>
        public const string achievement_ninja_slasher = "CgkI7PWMhvoCEAIQFA"; // <GPGSID>
        public const string achievement_fighter = "CgkI7PWMhvoCEAIQPA"; // <GPGSID>
        public const string achievement_chain__sickle_master = "CgkI7PWMhvoCEAIQBg"; // <GPGSID>
        public const string achievement_sword_master = "CgkI7PWMhvoCEAIQAQ"; // <GPGSID>
        public const string achievement_concealed_weapons = "CgkI7PWMhvoCEAIQHQ"; // <GPGSID>
        public const string leaderboard_most_kills = "CgkI7PWMhvoCEAIQZw"; // <GPGSID>
        public const string achievement_sword_swipes = "CgkI7PWMhvoCEAIQFQ"; // <GPGSID>
        public const string achievement_five_carat = "CgkI7PWMhvoCEAIQCg"; // <GPGSID>
        public const string achievement_coinoisseur = "CgkI7PWMhvoCEAIQQw"; // <GPGSID>
        public const string achievement_long_range = "CgkI7PWMhvoCEAIQJA"; // <GPGSID>
        public const string achievement_janka_test = "CgkI7PWMhvoCEAIQVQ"; // <GPGSID>
        public const string achievement_one_carat = "CgkI7PWMhvoCEAIQCQ"; // <GPGSID>
        public const string achievement_pointy = "CgkI7PWMhvoCEAIQUA"; // <GPGSID>
        public const string achievement_chain_attack = "CgkI7PWMhvoCEAIQLw"; // <GPGSID>
        public const string achievement_sai_you_later = "CgkI7PWMhvoCEAIQOQ"; // <GPGSID>
        public const string achievement_journeyman = "CgkI7PWMhvoCEAIQYw"; // <GPGSID>
        public const string achievement_warlord = "CgkI7PWMhvoCEAIQXg"; // <GPGSID>
        public const string achievement_soverign = "CgkI7PWMhvoCEAIQSw"; // <GPGSID>
        public const string achievement_sharpening_my_claws = "CgkI7PWMhvoCEAIQWg"; // <GPGSID>
        public const string achievement_sickle_with_it = "CgkI7PWMhvoCEAIQVw"; // <GPGSID>
        public const string achievement_ready_aim_fire = "CgkI7PWMhvoCEAIQJQ"; // <GPGSID>
        public const string achievement_dual_wield = "CgkI7PWMhvoCEAIQWw"; // <GPGSID>
        public const string achievement_chucking_stars = "CgkI7PWMhvoCEAIQIA"; // <GPGSID>
        public const string achievement_bonsai = "CgkI7PWMhvoCEAIQWA"; // <GPGSID>
        public const string achievement_sharpening_your_blades = "CgkI7PWMhvoCEAIQTA"; // <GPGSID>

}

